# -*- coding: utf-8 -*-
"""Clase 1 python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPgDkxyIsXIXscy7LFhT3DB5on8fjiU7
"""

print("¡Hola mundo!")#
print("¡Hola mundo ma!")
print("¡Hola mundo pa!")

# Pedir dos numeros al usuario
numero1 = float(input('Ingresa el primer numero'))
numero2 = float(input('Ingresa el primer numero'))

#Sumar los numeros
suma = numero1 + numero2

#Mostrar la suma
print('La suma es:', suma)

# Pedir dos numeros al usuario
numero1 = float(input('Ingresa el primer numero'))
numero2 = float(input('Ingresa el primer numero'))

#Resta los numeros
Resta = numero1 - numero2

#Mostrar la resta
print('La resta es:', Resta)

# Pedir dos numeros al usuario
numero1 = float(input('Ingresa el primer numero'))
numero2 = float(input('Ingresa el primer numero'))

#Multiplicacion los numeros
multiplicacion = numero1 * numero2

#Mostrar la multiplicacion
print('La multiplicacion es:', multiplicacion)

numero1 = float(input('Ingresa el primer numero: '))
numero2 = float(input('Ingresa el segundo numero: '))

# Realizar la división
if numero2 != 0:
    division = numero1 / numero2
    print('La división es:', division)
else:
    print('No se puede dividir por cero.')

nota1 = float(input("Nota 1: "))
nota2 = float(input("Nota 2: "))
nota3 = float(input("Nota 3: "))

promedio = (nota1 + nota2 + nota3) / 3

print("Promedio:", promedio)

nombre = input('Ingresa tu nombre: ')
edad = input('Ingresa tu edad: ')
materia = input('Ingresa tu materia: ')

print(f'Mi nombre es {nombre}')
print(f'Tengo {edad} años')
print(f'Estoy aprendiendo {materia}')



nombre = input('Ingresa tu nombre: ')
edad = input('Ingresa tu edad: ')
materia = input('Ingresa tu materia: ')

print('Mi nombre es ' + nombre)
print('Tengo ' + edad + ' años')
print('Estoy aprendiendo ' + materia)

nomre= 'Ana'
edad= 25
ciudad= 'Escazu'
print(nombre, edad, ciudad)

A = 10 + 9
B = 10 - 1
C = 10 * 43
D= 10 / 2


print(A+B)
print(A-C)
print(D*B)
print(C/B)

nombre = input('Cual es tu nombre: ')

print('Hola ' + nombre)
resto = input('cuenta me de tu vida ')

print(resto)

from ast import Or
Edad =int(input('Edad: '))
if Edad >= 18:
    print('Entra gratis')
    if Edad <= 25:
        print('Puedes votar')
else:
    print('No puede ingresar')

Nota =int(input('Nota: '))
if Nota <70:
    print('no paso')
    if Nota >= 70:
        print('Paso')
if Nota >= 80:
    print('Paso bien')
    if Nota == 100:
        print('Paso excelente')

else:
    print('No existe la nota')

###Pide numero positivo o negativo
numero =int(input('Nota: '))
if numero >0:
    print('Es positivo')
    if numero <0:
        print('Es negativo')
else:
  print ('Neutral')

for numero in range(1,10):
  print (numero)

numero = int(input('digite un numero'))
for i in range (1,11):
  print (numero, 'x', i,'=', numero*i)

contador = 1
while contador <=5:
  print(contador)
  contador = contador + 1

contador = 2
while contador <=20:
  print(contador)
  contador = contador + 2

#Mi proyecto Nombre, edad si es mayor de edad puede votar si no no puede
nombre = input("Nombre: ")
edad = int(input("Edad: "))

print("--------------------")
print("Nombre:", nombre)
print("Edad:", edad)

if edad >= 18:
    print("Puede votar")
else:
    print("Todavía no puede votar")

"""Mostrar tu nombre cinco veces usando for.
Pedir dos números y mostrar cuál es el mayor.
Pedir un número y decir si es par o impar.
Mostrar la tabla de multiplicar del 7.
Contar del 20 al 1.
Pedir cinco números y mostrar su suma.
Pedir tres edades y calcular el promedio
"""

nombre = "Luis Felipe"

for i in range(5):
    print(nombre)

numero1 = float(input("Pon el primer numero: "))
numero2 = float(input("pon el segundo numero: "))

if numero1 > numero2:
    print("El mayor es:", numero1)
if numero2 > numero1:
    print("El mayor es:", numero2)
if numero1 == numero2:
    print("Son iguales")

numero = int(input("Pone un número: "))

if numero % 2 == 0:
    print("Es par")
else:
    print("Es impar")

for i in range(1, 11):
    print("7 x", i, "=", 7 * i)

for i in range(20, 0, -1):
    print(i)

suma = 0

for i in range(5):
    num = float(input("pon un numero: "))
    suma = suma + num

print("La suma es:", suma)

edad1 = float(input("pon la primera edad: "))
edad2 = float(input("pon la segunda edad: "))
edad3 = float(input("pon la tercera edad: "))

promedio = (edad1 + edad2 + edad3) / 3

print("El promedio es:", promedio)

while True:
  print('\n=========================Menu Principal===============================')
  print('1. Saludar')
  print('2. Mostrar nombre')
  print('3. Sumar Numeros')
  print('4. Mostrar Promedio')
  print('5. Aplicar Analisis')
  print('6. Buscar Animal')
  print('7. Salir')

  opcion = input('Seleccione una opcion:')

  if opcion == '1':
      print('Hola, Bienvenido al programa')
  elif opcion == '2':
      nombre = input('Por favor, ingresa tu nombre para mostrarlo: ')
      print('Hola',nombre)
  elif opcion == '3':
       print("sumar numeros")
  elif opcion == '4':
       print("mostrar promedio")

  elif opcion == "5":
      print("Aplicando análisis...")

  elif opcion == "6":
      animal = input("¿Qué animal desea buscar? ")
      print("Buscando:", animal)

  elif opcion == "7":
      print("¡Hasta luego!")
      break

  else:
      print("Opción inválida. Intente nuevamente.")

while True:
    print("\n===== MENÚ PRINCIPAL =====")
    print("1. Saludar")
    print("2. Mostrar nombre")
    print("3. Sumar dos números")
    print("4. Calcular Promedio")
    print("5. Aplicar analisis")
    print("6. Buscar Animal")
    print("7. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        print("¡Hola! Bienvenido al programa.")

    elif opcion == "2":
        nombre = input("Digite su nombre: ")
        print("Hola", nombre)

    elif opcion == "3":
        num1 = float(input("Digite el primer número: "))
        num2 = float(input("Digite el segundo número: "))
        suma = num1 + num2
        print("La suma es:", suma)
    elif opcion == "4":
        nota1 = float(input("Digite la primera nota: "))
        nota2 = float(input("Digite la segunda nota: "))
        nota3 = float(input("Digite la tercera nota: "))
        promedio = (nota1 + nota2 + nota3) / 3
        print("El promedio es:", promedio)

    elif opcion == '5':
        print('Aplicar analisis.')

    elif opcion == '6':
        animal = input('Que animal desea buscar: ')
        print('Buscando:', animal)

    elif opcion == '7':
        print("Gracias por utilizar el programa.")
        break

    else:
        print("Opción inválida. Intente nuevamente.")

import pandas as pd

datos = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}

"ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
           11, 12, 13, 14, 15, 16, 17, 18, 19, 20],

    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],

    "Especie": [
        "Panthera leo", "Panthera tigris", "Loxodonta africana",
        "Giraffa camelopardalis", "Equus quagga", "Macaca",
        "Gorilla gorilla", "Ursus arctos", "Ailuropoda melanoleuca",
        "Macropus", "Hippopotamus amphibius", "Ceratotherium simum",
        "Crocodylus", "Python", "Aquila", "Spheniscidae",
        "Phoenicopterus", "Testudines", "Canis lupus", "Vulpes vulpes"
    ],

    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],

    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],

    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],

    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
# Crear DataFrame
df = pd.DataFrame(datos)

import pandas as pd

# 1. DATOS DE ESTUDIANTES
datos_estudiantes = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}

# 2. DATOS DE ANIMALES
datos_animales = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],
    "Especie": [
        "Panthera leo", "Panthera tigris", "Loxodonta africana",
        "Giraffa camelopardalis", "Equus quagga", "Macaca",
        "Gorilla gorilla", "Ursus arctos", "Ailuropoda melanoleuca",
        "Macropus", "Hippopotamus amphibius", "Ceratotherium simum",
        "Crocodylus", "Python", "Aquila", "Spheniscidae",
        "Phoenicopterus", "Testudines", "Canis lupus", "Vulpes vulpes"
    ],
    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],
    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],
    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],
    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}

# Creación de DataFrames
df_estudiantes = pd.DataFrame(datos_estudiantes)
df_animales = pd.DataFrame(datos_animales)

while True:
    print("\n===== MENÚ PRINCIPAL =====")
    print("1. Saludar")
    print("2. Mostrar nombre")
    print("3. Sumar dos números")
    print("4. Calcular Promedio")
    print("5. Aplicar análisis")
    print("6. Buscar Animal")
    print("7. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        print("¡Hola! Bienvenido al programa.")

    elif opcion == "2":
        nombre = input("Digite su nombre: ")
        print("Hola", nombre)

    elif opcion == "3":
        num1 = float(input("Digite el primer número: "))
        num2 = float(input("Digite el segundo número: "))
        suma = num1 + num2
        print("La suma es:", suma)

    elif opcion == "4":
        nota1 = float(input("Digite la primera nota: "))
        nota2 = float(input("Digite la segunda nota: "))
        nota3 = float(input("Digite la tercera nota: "))
        promedio = (nota1 + nota2 + nota3) / 3
        print("El promedio es:", promedio)

    elif opcion == "5":
        while True:
            print("\n--- MENÚ ANÁLISIS ---")
            print("1. Mostrar tabla")
            print("2. Mostrar información")
            print("3. Mostrar estadística")
            print("4. Mostrar estudiante")
            print("5. Mostrar aprobados")
            print("6. Mostrar reprobados")
            print("7. Promedio de notas")
            print("8. Promedio por curso")
            print("9. Regresar")

            sub_opcion = input("Seleccione una opción: ")

            if sub_opcion == "1":
                print("\n--- TABLA DE DATOS ---")
                print(df_estudiantes)

            elif sub_opcion == "2":
                print("\n--- INFORMACIÓN GENERAL ---")
                print(df_estudiantes.info())

            elif sub_opcion == "3":
                print("\n--- ESTADÍSTICAS DESCRIPTIVAS ---")
                print(df_estudiantes.describe())

            elif sub_opcion == "4":
                busqueda = input("\nDigite el nombre o ID del estudiante: ")
                encontrado = False

                for index, fila in df_estudiantes.iterrows():
                    if str(fila.get("ID")) == busqueda or str(fila.get("Nombre")) == busqueda:
                        print("\n--- ESTUDIANTE ENCONTRADO ---")
                        print(f"ID: {fila.get('ID')} | Nombre: {fila.get('Nombre')} | Curso: {fila.get('Curso')} | Nota: {fila.get('Nota')}")
                        encontrado = True
                        break

                if not encontrado:
                    print("\nNo se encontró ningún estudiante con esa información.")

            elif sub_opcion == "5":
                print("\n--- APROBADOS (Nota >= 70) ---")
                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Nota") >= 70:
                        print(f"Nombre: {fila.get('Nombre')} | Nota: {fila.get('Nota')}")

            elif sub_opcion == "6":
                print("\n--- REPROBADOS (Nota < 70) ---")
                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Nota") < 70:
                        print(f"Nombre: {fila.get('Nombre')} | Nota: {fila.get('Nota')}")

            elif sub_opcion == "7":
                # Cálculo de promedio manual sin usar .mean()
                suma_total = 0
                cantidad = 0
                for index, fila in df_estudiantes.iterrows():
                    suma_total += fila.get("Nota")
                    cantidad += 1

                promedio_general = suma_total / cantidad
                print(f"\nEl promedio general de notas es: {promedio_general}")

            elif sub_opcion == "8":
                curso_buscar = input("\nDigite el curso (Python/SQL): ")
                suma_curso = 0
                cont_curso = 0

                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Curso") == curso_buscar:
                        suma_curso += fila.get("Nota")
                        cont_curso += 1

                if cont_curso > 0:
                    print(f"\nEl promedio para el curso {curso_buscar} es: {suma_curso / cont_curso}")
                else:
                    print("\nNo se encontraron datos para ese curso.")

            elif sub_opcion == "9":
                print("Regresando al menú principal...")
                break

            else:
                print("Opción inválida. Intente nuevamente.")

    elif opcion == "6":
        busqueda_animal = input("\n¿Qué animal desea buscar? ")
        encontrado = False

        for index, fila in df_animales.iterrows():
            if str(fila.get("ID")) == busqueda_animal or str(fila.get("Animal")) == busqueda_animal:
                print("\n--- ANIMAL ENCONTRADO ---")
                print(f"ID: {fila.get('ID')} | Animal: {fila.get('Animal')} | Especie: {fila.get('Especie')} | Hábitat: {fila.get('Habitat')}")
                encontrado = True
                break

        if not encontrado:
            print(f"\nNo se encontró ningún animal con la información: '{busqueda_animal}'.")

    elif opcion == "7":
        print("Gracias por utilizar el programa.")
        break

    else:
        print("Opción inválida. Intente nuevamente.")

import pandas as pd

datos_estudiantes = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}

datos_animales = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],
    "Especie": [
        "Panthera leo", "Panthera tigris", "Loxodonta africana",
        "Giraffa camelopardalis", "Equus quagga", "Macaca",
        "Gorilla gorilla", "Ursus arctos", "Ailuropoda melanoleuca",
        "Macropus", "Hippopotamus amphibius", "Ceratotherium simum",
        "Crocodylus", "Python", "Aquila", "Spheniscidae",
        "Phoenicopterus", "Testudines", "Canis lupus", "Vulpes vulpes"
    ],
    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],
    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],
    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],
    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}
df_estudiantes = pd.DataFrame(datos_estudiantes)
df_animales = pd.DataFrame(datos_animales)

while True:
    print("\n===== MENÚ PRINCIPAL =====")
    print("1. Saludar")
    print("2. Mostrar nombre")
    print("3. Sumar dos números")
    print("4. Calcular Promedio")
    print("5. Aplicar análisis")
    print("6. Buscar Animal")
    print("7. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        print("¡Hola! Bienvenido al programa.")

    elif opcion == "2":
        nombre = input("Digite su nombre: ")
        print("Hola", nombre)

    elif opcion == "3":
        num1 = float(input("Digite el primer número: "))
        num2 = float(input("Digite el segundo número: "))
        suma = num1 + num2
        print("La suma es:", suma)

    elif opcion == "4":
        nota1 = float(input("Digite la primera nota: "))
        nota2 = float(input("Digite la segunda nota: "))
        nota3 = float(input("Digite la tercera nota: "))
        promedio = (nota1 + nota2 + nota3) / 3
        print("El promedio es:", promedio)

    elif opcion == "5":
        while True:
            print("\n--- MENÚ ANÁLISIS ---")
            print("1. Mostrar tabla")
            print("2. Mostrar información")
            print("3. Mostrar estadística")
            print("4. Mostrar estudiante")
            print("5. Mostrar aprobados")
            print("6. Mostrar reprobados")
            print("7. Promedio de notas")
            print("8. Promedio por curso")
            print("9. Regresar")

            sub_opcion = input("Seleccione una opción: ")

            if sub_opcion == "1":
                print("\n--- tabla de datos ---")
                print(df_estudiantes)

            elif sub_opcion == "2":
                print("\n--- informacion general ---")
                print(df_estudiantes.info())

            elif sub_opcion == "3":
                print("\n--- estadistica descriptiva ---")
                print(df_estudiantes.describe())

            elif sub_opcion == "4":
                busqueda = input("\nDigite el nombre o ID del estudiante: ")
                encontrado = False

                for index, fila in df_estudiantes.iterrows():
                    if str(fila.get("ID")) == busqueda or str(fila.get("Nombre")) == busqueda:
                        print("\n--- estudiante encontrado ---")
                        print(f"ID: {fila.get('ID')}, Nombre: {fila.get('Nombre')}, Curso: {fila.get('Curso')}, Nota: {fila.get('Nota')}")
                        encontrado = True
                        break

                if not encontrado:
                    print("\nNo se encontró ningún estudiante con esa información.")

            elif sub_opcion == "5":
                print("\n aprobados (Nota >= 70)")
                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Nota") >= 70:
                        print(f"Nombre: {fila.get('Nombre')}, Nota: {fila.get('Nota')}")

            elif sub_opcion == "6":
                print("\nreprobados (Nota < 70)")
                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Nota") < 70:
                        print(f"Nombre: {fila.get('Nombre')}, Nota: {fila.get('Nota')}")

            elif sub_opcion == "7":
                suma_total = 0
                cantidad = 0
                for index, fila in df_estudiantes.iterrows():
                    suma_total += fila.get("Nota")
                    cantidad += 1

                promedio_general = suma_total / cantidad
                print(f"\nEl promedio general de notas es: {promedio_general}")

            elif sub_opcion == "8":
                curso_buscar = input("\nDigite el curso (Python/SQL): ")
                suma_curso = 0
                cont_curso = 0

                for index, fila in df_estudiantes.iterrows():
                    if fila.get("Curso") == curso_buscar:
                        suma_curso += fila.get("Nota")
                        cont_curso += 1

                if cont_curso > 0:
                    print(f"\nEl promedio para el curso {curso_buscar} es: {suma_curso / cont_curso}")
                else:
                    print("\nNo se encontraron datos para ese curso.")

            elif sub_opcion == "9":
                print("Regresando al menú principal...")
                break

            else:
                print("Opción inválida. Intente nuevamente.")

    elif opcion == "6":
        busqueda_animal = input("\n¿Qué animal desea buscar? ")


        for index, fila in df_animales.iterrows():
            if str(fila.get("ID")) == busqueda_animal or str(fila.get("Animal")) == busqueda_animal:
                print("\n--- animal encontrado ---")
                print(f"ID: {fila.get('ID')}, Animal: {fila.get('Animal')}, Especie: {fila.get('Especie')}, Hábitat: {fila.get('Habitat')}")

                break

        if not encontrado:
            print(f"\nNo se encontró ningún animal con la información: '{busqueda_animal}'.")

    elif opcion == "7":
        print("Gracias por utilizar el programa.")
        break

    else:
        print("Opción inválida. Intente nuevamente.")

# ==========================================================
# TABLA DE ESTUDIANTES
# ==========================================================

datos = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}

df_estudiantes = pd.DataFrame(datos)


# ==========================================================
# TABLA DE ANIMALES
# ==========================================================

animales = {
    "ID": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],

    "Especie": [
        "Panthera leo",
        "Panthera tigris",
        "Loxodonta africana",
        "Giraffa camelopardalis",
        "Equus quagga",
        "Macaca",
        "Gorilla gorilla",
        "Ursus arctos",
        "Ailuropoda melanoleuca",
        "Macropus",
        "Hippopotamus amphibius",
        "Ceratotherium simum",
        "Crocodylus",
        "Python",
        "Aquila",
        "Spheniscidae",
        "Phoenicopterus",
        "Testudines",
        "Canis lupus",
        "Vulpes vulpes"
    ],

    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],

    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],

    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],

    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}

df_animales = pd.DataFrame(animales)

def analisis_datos():

    # Datos del DataFrame
    datos = {
        "Producto": [
            "Laptop",
            "Mouse",
            "Teclado",
            "Monitor",
            "Laptop",
            "Mouse",
            "Monitor",
            "Teclado"
        ],

        "Categoria": [
            "Computo",
            "Accesorios",
            "Accesorios",
            "Computo",
            "Computo",
            "Accesorios",
            "Computo",
            "Accesorios"
        ],

        "Cantidad": [2,10,5,3,1,8,4,6],


        "Precio": [  750000, 15000, 25000, 180000, 750000, 15000, 180000, 25000 ]
    }

    # Crear DataFrame
    df = pd.DataFrame(datos)
# ==========================================================
# MENÚ PRINCIPAL
# ==========================================================

while True:

    print("\n================================")
    print("        MENÚ PRINCIPAL")
    print("================================")
    print("1. Saludar")
    print("2. Mostrar Nombre")
    print("3. Sumar Números")
    print("4. Mostrar Promedio")
    print("5. Analizar Tabla de Estudiantes")
    print("6. Buscar Animal")
    print("7. Mostrar Tabla de Animales")
    print("8. Salir")
    print("================================")

    opcion = input("Seleccione una opción: ")


    # ======================================================
    # OPCIÓN 1
    # ======================================================

    if opcion == "1":

        print("\n¡Hola! Bienvenido al programa.")


    # ======================================================
    # OPCIÓN 2
    # ======================================================

    elif opcion == "2":

        nombre = input("\nDigite su nombre: ")

        print("Su nombre es:", nombre)


    # ======================================================
    # OPCIÓN 3
    # ======================================================

    elif opcion == "3":

        numero1 = float(input("\nDigite el primer número: "))
        numero2 = float(input("Digite el segundo número: "))

        suma = numero1 + numero2

        print("La suma es:", suma)


    # ======================================================
    # OPCIÓN 4
    # ======================================================

    elif opcion == "4":

        n1 = float(input("\nDigite la primera nota: "))
        n2 = float(input("Digite la segunda nota: "))
        n3 = float(input("Digite la tercera nota: "))

        promedio = (n1 + n2 + n3) / 3

        print("El promedio es:", promedio)


    # ======================================================
    # OPCIÓN 5
    # ======================================================

    elif opcion == "5":

        while True:

            print("\n================================")
            print("       ANÁLISIS DE ESTUDIANTES")
            print("================================")
            print("1. Mostrar tabla")
            print("2. Mostrar información")
            print("3. Mostrar estadísticas")
            print("4. Buscar estudiante")
            print("5. Mostrar estudiantes aprobados")
            print("6. Mostrar estudiantes reprobados")
            print("7. Promedio de notas")
            print("8. Promedio por curso")
            print("9. Regresar")
            print("================================")

            consulta = input("Seleccione una opción: ")


            # ----------------------------------------------
            # MOSTRAR TABLA
            # ----------------------------------------------

            if consulta == "1":

                print("\n===== TABLA DE ESTUDIANTES =====")

                print(df_estudiantes)


            # ----------------------------------------------
            # INFORMACIÓN
            # ----------------------------------------------

            elif consulta == "2":

                print("\n===== INFORMACIÓN =====")

                df_estudiantes.info()


            # ----------------------------------------------
            # ESTADÍSTICAS
            # ----------------------------------------------

            elif consulta == "3":

                print("\n===== ESTADÍSTICAS =====")

                print(df_estudiantes.describe())


            # ----------------------------------------------
            # BUSCAR ESTUDIANTE
            # ----------------------------------------------

            elif consulta == "4":

                nombre = input(
                    "\nDigite el nombre del estudiante: "
                )

                resultado = df_estudiantes[
                    df_estudiantes["Nombre"].str.lower()
                    == nombre.lower()
                ]

                if resultado.empty:

                    print("\nEstudiante no encontrado.")

                else:

                    print("\n===== ESTUDIANTE =====")

                    print(resultado)


            # ----------------------------------------------
            # APROBADOS
            # ----------------------------------------------

            elif consulta == "5":

                aprobados = df_estudiantes[
                    df_estudiantes["Nota"] >= 70
                ]

                print("\n===== ESTUDIANTES APROBADOS =====")

                print(aprobados)


            # ----------------------------------------------
            # REPROBADOS
            # ----------------------------------------------

            elif consulta == "6":

                reprobados = df_estudiantes[
                    df_estudiantes["Nota"] < 70
                ]

                print("\n===== ESTUDIANTES REPROBADOS =====")

                print(reprobados)


            # ----------------------------------------------
            # PROMEDIO
            # ----------------------------------------------

            elif consulta == "7":

                promedio = df_estudiantes["Nota"].mean()

                print("\n===== PROMEDIO GENERAL =====")

                print("Promedio:", round(promedio, 2))


            # ----------------------------------------------
            # PROMEDIO POR CURSO
            # ----------------------------------------------

            elif consulta == "8":

                promedio_curso = df_estudiantes.groupby(
                    "Curso"
                )["Nota"].mean()

                print("\n===== PROMEDIO POR CURSO =====")

                print(promedio_curso.round(2))

            # ----------------------------------------------
            # Mostrar profesor
            # ----------------------------------------------

            elif consulta == "9":

                print("\n===== Nombre Profesor =====")

                print('\nProfesor: Berman)
            # ----------------------------------------------
            # REGRESAR
            # ----------------------------------------------

            elif consulta == "10":

                break

            else:

                print("\nOpción inválida.")


    # ======================================================
    # OPCIÓN 6 - BUSCAR ANIMAL
    # ======================================================

    elif opcion == "6":

        animal = input(
            "\n¿Qué animal desea buscar? "
        )

        resultado = df_animales[
            df_animales["Animal"].str.lower()
            == animal.lower()
        ]

        if resultado.empty:

            print("\nAnimal no encontrado.")

        else:

            print("\n===== ANIMAL ENCONTRADO =====")

            print(resultado.to_string(index=False))


    # ======================================================
    # OPCIÓN 7 - MOSTRAR ANIMALES
    # ======================================================

    elif opcion == "7":

        print("\n===== TABLA DE ANIMALES =====")

        print(df_animales.to_string(index=False))

  # ======================================================
    # OPCIÓN 8 - Mostrar profesor
    # ======================================================

    elif opcion == "8":

        print("\n===== TABLA DE ANIMALES =====")

        print(df_animales.to_string(index=False))


    # ======================================================
    # OPCIÓN 8 - SALIR
    # ======================================================

    elif opcion == "8":

        print("\n¡Hasta luego!")

        break


    else:

        print("\nOpción inválida.")

import pandas as pd

datos_estudiantes = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}

df_estudiantes = pd.DataFrame(datos_estudiantes)


animales = {
    "ID": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],

    "Especie": [
        "Panthera leo",
        "Panthera tigris",
        "Loxodonta africana",
        "Giraffa camelopardalis",
        "Equus quagga",
        "Macaca",
        "Gorilla gorilla",
        "Ursus arctos",
        "Ailuropoda melanoleuca",
        "Macropus",
        "Hippopotamus amphibius",
        "Ceratotherium simum",
        "Crocodylus",
        "Python",
        "Aquila",
        "Spheniscidae",
        "Phoenicopterus",
        "Testudines",
        "Canis lupus",
        "Vulpes vulpes"
    ],

    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],

    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],

    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],

    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}

df_animales = pd.DataFrame(animales)

def analisis_datos():

    # Datos del DataFrame
    datos = {
        "Producto": [
            "Laptop",
            "Mouse",
            "Teclado",
            "Monitor",
            "Laptop",
            "Mouse",
            "Monitor",
            "Teclado"
        ],

        "Categoria": [
            "Computo",
            "Accesorios",
            "Accesorios",
            "Computo",
            "Computo",
            "Accesorios",
            "Computo",
            "Accesorios"
        ],

        "Cantidad": [2,10,5,3,1,8,4,6],


        "Precio": [  750000, 15000, 25000, 180000, 750000, 15000, 180000, 25000 ]
    }

    # Crear DataFrame
    df = pd.DataFrame(datos)
# ==========================================================
# MENÚ PRINCIPAL
# ==========================================================

while True:

    print("\n================================")
    print("        MENÚ PRINCIPAL")
    print("================================")
    print("1. Saludar")
    print("2. Mostrar Nombre")
    print("3. Sumar Números")
    print("4. Mostrar Promedio")
    print("5. Analizar Tabla de Estudiantes")
    print("6. Buscar Animal")
    print("7. Mostrar Tabla de Animales")
    print("8. Salir")
    print("================================")

    opcion = input("Seleccione una opción: ")


    # ======================================================
    # OPCIÓN 1
    # ======================================================

    if opcion == "1":

        print("\n¡Hola! Bienvenido al programa.")


    # ======================================================
    # OPCIÓN 2
    # ======================================================

    elif opcion == "2":

        nombre = input("\nDigite su nombre: ")

        print("Su nombre es:", nombre)


    # ======================================================
    # OPCIÓN 3
    # ======================================================

    elif opcion == "3":

        numero1 = float(input("\nDigite el primer número: "))
        numero2 = float(input("Digite el segundo número: "))

        suma = numero1 + numero2

        print("La suma es:", suma)


    # ======================================================
    # OPCIÓN 4
    # ======================================================

    elif opcion == "4":

        n1 = float(input("\nDigite la primera nota: "))
        n2 = float(input("Digite la segunda nota: "))
        n3 = float(input("Digite la tercera nota: "))

        promedio = (n1 + n2 + n3) / 3

        print("El promedio es:", promedio)


    # ======================================================
    # OPCIÓN 5
    # ======================================================

    elif opcion == "5":

        while True:

            print("\n================================")
            print("       ANÁLISIS DE ESTUDIANTES")
            print("================================")
            print("1. Mostrar tabla")
            print("2. Mostrar información")
            print("3. Mostrar estadísticas")
            print("4. Buscar estudiante")
            print("5. Mostrar estudiantes aprobados")
            print("6. Mostrar estudiantes reprobados")
            print("7. Promedio de notas")
            print("8. Promedio por curso")
            print("9. Mostrar profesor")
            print("10. Regresar")
            print("================================")

            consulta = input("Seleccione una opción: ")


            # ----------------------------------------------
            # MOSTRAR TABLA
            # ----------------------------------------------

            if consulta == "1":

                print("\n===== TABLA DE ESTUDIANTES =====")

                print(df_estudiantes)


            # ----------------------------------------------
            # INFORMACIÓN
            # ----------------------------------------------

            elif consulta == "2":

                print("\n===== INFORMACIÓN =====")

                df_estudiantes.info()


            # ----------------------------------------------
            # ESTADÍSTICAS
            # ----------------------------------------------

            elif consulta == "3":

                print("\n===== ESTADÍSTICAS =====")

                print(df_estudiantes.describe())


            # ----------------------------------------------
            # BUSCAR ESTUDIANTE
            # ----------------------------------------------

            elif consulta == "4":

                nombre = input(
                    "\nDigite el nombre del estudiante: "
                )

                resultado = df_estudiantes[
                    df_estudiantes["Nombre"].str.lower()
                    == nombre.lower()
                ]

                if resultado.empty:

                    print("\nEstudiante no encontrado.")

                else:

                    print("\n===== ESTUDIANTE =====")

                    print(resultado)


            # ----------------------------------------------
            # APROBADOS
            # ----------------------------------------------

            elif consulta == "5":

                aprobados = df_estudiantes[
                    df_estudiantes["Nota"] >= 70
                ]

                print("\n===== ESTUDIANTES APROBADOS =====")

                print(aprobados)


            # ----------------------------------------------
            # REPROBADOS
            # ----------------------------------------------

            elif consulta == "6":

                reprobados = df_estudiantes[
                    df_estudiantes["Nota"] < 70
                ]

                print("\n===== ESTUDIANTES REPROBADOS =====")

                print(reprobados)


            # ----------------------------------------------
            # PROMEDIO
            # ----------------------------------------------

            elif consulta == "7":

                promedio = df_estudiantes["Nota"].mean()

                print("\n===== PROMEDIO GENERAL =====")

                print("Promedio:", round(promedio, 2))


            # ----------------------------------------------
            # PROMEDIO POR CURSO
            # ----------------------------------------------

            elif consulta == "8":

                promedio_curso = df_estudiantes.groupby(
                    "Curso"
                )["Nota"].mean()

                print("\n===== PROMEDIO POR CURSO =====")

                print(promedio_curso.round(2))

            # ----------------------------------------------
            # Mostrar profesor
            # ----------------------------------------------

            elif consulta == "9":

                print("\n===== Nombre Profesor =====")

                print('\nProfesor: Berman')
            # ----------------------------------------------
            # REGRESAR
            # ----------------------------------------------

            elif consulta == "10":

                break

            else:

                print("\nOpción inválida.")


    # ======================================================
    # OPCIÓN 6 - BUSCAR ANIMAL
    # ======================================================

    elif opcion == "6":

        animal = input(
            "\n¿Qué animal desea buscar? "
        )

        resultado = df_animales[
            df_animales["Animal"].str.lower()
            == animal.lower()
        ]

        if resultado.empty:

            print("\nAnimal no encontrado.")

        else:

            print("\n===== ANIMAL ENCONTRADO =====")

            print(resultado.to_string(index=False))


    # ======================================================
    # OPCIÓN 7 - MOSTRAR ANIMALES
    # ======================================================

    elif opcion == "7":

        print("\n===== TABLA DE ANIMALES =====")

        print(df_animales.to_string(index=False))

  # ======================================================
    # OPCIÓN 8 - Salir
    # ======================================================

    elif opcion == "8":

        print("\n¡Hasta luego!")

        break


    else:

        print("\nOpción inválida.")